<?php

namespace dekuan\debookacl;


class CBookAcl
{
	//
	//	PERMISSION, max value is 4294967296 ( 1 << 32 )
	//
	const PERMISSION_GROUP_READ		= 1 << 0x00;
	const PERMISSION_GROUP_WRITE		= 1 << 0x01;
	const PERMISSION_MEMBER_READ		= 1 << 0x02;
	const PERMISSION_MEMBER_WRITE		= 1 << 0x03;
	const PERMISSION_CLASSROOM_READ		= 1 << 0x04;
	const PERMISSION_CLASSROOM_WRITE	= 1 << 0x05;
	const PERMISSION_COURSE_READ		= 1 << 0x06;
	const PERMISSION_COURSE_WRITE		= 1 << 0x07;
	const PERMISSION_CONSUME_READ		= 1 << 0x08;
	const PERMISSION_CONSUME_WRITE		= 1 << 0x09;
	const PERMISSION_TOP_UP_READ		= 1 << 0x0A;
	const PERMISSION_TOP_UP_WRITE		= 1 << 0x0B;
	const PERMISSION_COMMENT_READ		= 1 << 0x0C;
	const PERMISSION_COMMENT_WRITE		= 1 << 0x0D;
	const PERMISSION_COMMENT_TAG_READ	= 1 << 0x0E;
	const PERMISSION_COMMENT_TAG_WRITE	= 1 << 0x0F;
	const PERMISSION_FAVORITE_READ		= 1 << 0x10;
	const PERMISSION_FAVORITE_WRITE		= 1 << 0x11;


	//
	//	Roles
	//
	const ROLE_ADMINISTRATOR		= self::PERMISSION_GROUP_READ |
						self::PERMISSION_GROUP_WRITE |
						self::PERMISSION_MEMBER_READ |
						self::PERMISSION_MEMBER_WRITE |
						self::PERMISSION_CLASSROOM_READ |
						self::PERMISSION_CLASSROOM_WRITE |
						self::PERMISSION_COURSE_READ |
						self::PERMISSION_COURSE_WRITE |
						self::PERMISSION_CONSUME_READ |
						self::PERMISSION_CONSUME_WRITE |
						self::PERMISSION_TOP_UP_READ |
						self::PERMISSION_TOP_UP_WRITE |
						self::PERMISSION_COMMENT_READ |
						self::PERMISSION_COMMENT_WRITE |
						self::PERMISSION_COMMENT_TAG_READ |
						self::PERMISSION_COMMENT_TAG_WRITE |
						self::PERMISSION_FAVORITE_READ |
						self::PERMISSION_FAVORITE_WRITE;


	const ROLE_ASSISTANT			= self::PERMISSION_GROUP_READ |
						self::PERMISSION_MEMBER_READ |
						self::PERMISSION_CLASSROOM_READ |
						self::PERMISSION_COURSE_READ |
						self::PERMISSION_CONSUME_READ |
						self::PERMISSION_TOP_UP_READ |
						self::PERMISSION_COMMENT_READ;


	const ROLE_TEACHER			= self::PERMISSION_GROUP_READ |
						self::PERMISSION_MEMBER_READ |
						self::PERMISSION_CLASSROOM_READ |
						self::PERMISSION_COURSE_READ |
						self::PERMISSION_COURSE_WRITE |
						self::PERMISSION_CONSUME_READ |
						self::PERMISSION_TOP_UP_READ |
						self::PERMISSION_COMMENT_READ |
						self::PERMISSION_COMMENT_WRITE |
						self::PERMISSION_FAVORITE_READ |
						self::PERMISSION_FAVORITE_WRITE;


	const ROLE_STUDENT			= self::PERMISSION_GROUP_READ |
						self::PERMISSION_MEMBER_READ |
						self::PERMISSION_CLASSROOM_READ |
						self::PERMISSION_COURSE_READ |
						self::PERMISSION_CONSUME_READ |
						self::PERMISSION_CONSUME_WRITE |
						self::PERMISSION_CONSUME_READ |
						self::PERMISSION_CONSUME_WRITE |
						self::PERMISSION_COMMENT_READ |
						self::PERMISSION_COMMENT_WRITE |
						self::PERMISSION_FAVORITE_READ |
						self::PERMISSION_FAVORITE_WRITE;

}